
development:
  adapter: mysql2
  encoding: utf8
  database: local_database
  username: debina-sys-maint
  password: bJEvc1d5RjPaV4Ze
  host: localhostt
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: local_database
  username: debian-sys-maint
  password: bJEvc1d5RjPaV4Ze
  host: localhost
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: local_database
  username: debina-sys-maint
  password: bJEvc1d5RjPaV4Ze
  host: localhostt
  port: 3306
